#!/usr/bin/env python
# From: See https://github.com/sdenel/highlight
import sys
import re

to_highlight = sys.argv[-1]

bash_color = "\033[1;31m" # red

regex = re.compile(re.escape(to_highlight), re.IGNORECASE)

for line in sys.stdin.readlines():
    line_colored = regex.sub(bash_color + to_highlight + "\033[0m", line)
    sys.stdout.write(line_colored)
