#!/usr/bin/env python
# From: See https://github.com/sdenel/highlight
import sys
import re

to_highlight = sys.argv[-1]

for line in sys.stdin.readlines():
    line_colored = re.sub(r"(?i)(" + re.escape(to_highlight) +")", r"\033[1;31m\1\033[0m", line )
    sys.stdout.write(line_colored)

